server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/powerup
    username: root
    password: Tr1n1tyfs
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "Reto Pragma"
appVersion: "1.0.0"
